// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwSOlk0DsXyFD5IvwBYXtgVo8vxMr-3Q',
    appId: '1:1039438101500:web:d46e91f98a55deebfa9079',
    messagingSenderId: '1039438101500',
    projectId: 'quakewatch-527c6',
    authDomain: 'quakewatch-527c6.firebaseapp.com',
    storageBucket: 'quakewatch-527c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0sdC8uRAYkiamtmLhdApxgmh9l27hGk',
    appId: '1:1039438101500:android:6e58675b9d256923fa9079',
    messagingSenderId: '1039438101500',
    projectId: 'quakewatch-527c6',
    storageBucket: 'quakewatch-527c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzGRW8pjPTrO8Ngmk5UncYhiVwNg6V0k',
    appId: '1:1039438101500:ios:18da52848076751bfa9079',
    messagingSenderId: '1039438101500',
    projectId: 'quakewatch-527c6',
    storageBucket: 'quakewatch-527c6.appspot.com',
    iosBundleId: 'com.example.quakewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIzGRW8pjPTrO8Ngmk5UncYhiVwNg6V0k',
    appId: '1:1039438101500:ios:fb065a69887e1265fa9079',
    messagingSenderId: '1039438101500',
    projectId: 'quakewatch-527c6',
    storageBucket: 'quakewatch-527c6.appspot.com',
    iosBundleId: 'com.example.quakewatch.RunnerTests',
  );
}
